# @package agent

# common
_target_: agent.sac.SACAgent
name: sac
reward_free: ${reward_free}
obs_type: ??? # to be specified later
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
action_range: ??? # to be specified later
save_dir: ??? # to be specified later
maze_type: ${maze_type}
device: ${device}
dtype: ${dtype}
maze_parent: ??? # to be specified later

update_every_steps: 2
num_expl_steps: ??? # to be specified later
hidden_dim: 1024
feature_dim: 1024
nstep: 1
batch_size: 512
use_tb: ${use_tb}
use_wandb: ${use_wandb}


maximum_timestep: 1000

# critic (SAC)
critic_target_tau: 0.005
critic_lr : 3e-4
critic_target_update_frequency: 2

# actor, alpha (SAC)
actor_update_frequency: 2
actor_lr : 3e-4
alpha_lr : 3e-4
log_std_bounds: [-5, 2] 
init_alpha: 0.2
use_auto_alpha: False

# fine-tuning
init_critic: false

# encoder
encoder_lr: 3e-4
